version: 2.0
jobs:
  build:
    docker:
      - image: node:16.13.1

    working_directory: ~/bank-xyz-ui

    deploy-dev:
      machine: true
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: yarn test

      - run: yarn lint

      - run: yarn build
      - run:
          name: Build and push Docker image to Heroku
          command: |
            sudo curl https://cli-assets.heroku.com/install.sh | sh
              HEROKU_API_KEY=${9c432291-164b-40c6-8aa7-2322c3ffa826} heroku container:login
              HEROKU_API_KEY=${9c432291-164b-40c6-8aa7-2322c3ffa826} heroku container:push -a xyz-bank-dev web
              HEROKU_API_KEY=${9c432291-164b-40c6-8aa7-2322c3ffa826} heroku container:release -a xyz-bank-dev web      