orbs: 
  heroku: circleci/heroku@1.2.6
version: 2.1
jobs:
  build:
    docker:
      - image: node:16.13.1
    working_directory: ~/bank-xyz-ui
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: Install dependencies
          command:
            yarn install
      - run:
          name: Install serve
          command:
            npm install serve -g

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: 
          name: Running lint
          command: yarn lint          

      # run tests!
      - run: 
          name: Running tests
          command: yarn test

      - run:
          name: Setup branch environment variable
          command: >
            if [ "$CIRCLE_BRANCH" = "master" ]; then
              echo 'export BRANCH_MAP="prod"' >> $BASH_ENV;
            elif [ "$CIRCLE_BRANCH" = "release" ]; then
              echo 'export BRANCH_MAP="qa"' >> $BASH_ENV;
            else
              echo 'export BRANCH_MAP="dev"' >> $BASH_ENV;
            fi
      - run:
          name: Build the project
          command: yarn build -- -c ${BRANCH_MAP} --no-progress
workflows:
  heroku_deploy:
     jobs:
       - build
       - heroku/deploy-via-git:
           force: true
           requires:
             - build # only run deploy-via-git job if the build job has completed
           filters:
             branches:
               only: 
                 - master # only run deploy-via-git job on some of this branches
                 - develop
                 - release